In [14]:
import seaborn as sns

In [15]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [16]:
df.shape

(150, 5)

In [17]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(1)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [20]:
X = df.iloc[:, :-1]
y = df["target"] 

In [22]:
##train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
# Create a scaler
scaler = StandardScaler()

In [25]:
X_train_scaled = scaler.fit_transform(X_train)

In [26]:
X_test_scaled = scaler.transform(X_test)

In [27]:
from sklearn.svm import SVC

In [28]:
svc=SVC(kernel='linear')

In [31]:
svc.fit(X_train_scaled, y_train)

SVC(kernel='linear')

In [32]:
## Prediction
y_pred=svc.predict(X_test_scaled)

In [33]:
from sklearn.metrics import classification_report,confusion_matrix

In [34]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.93      0.97        15
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.98        38
weighted avg       0.98      0.97      0.97        38

[[11  0  0]
 [ 0 14  1]
 [ 0  0 12]]


In [35]:
import pickle

In [36]:
# Create a pickle file and write the data
with open('model.pkl', 'wb') as file:
    pickle.dump(svc, file)

In [37]:
# Create a pickle file and write the data
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)